In [1]:
import pandas as pd

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
sea_levels = pd.read_csv('./Datasets/25_Change_in_Mean_Sea_Levels.csv')
sea_levels.head()

,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,Measure,Date,Value
0,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Arabian Sea,D10/17/1992,-62.65
1,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Atlantic Ocean,D10/17/1992,2.94
2,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Bay Bengal,D10/17/1992,9.81
3,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Bering Sea,D10/17/1992,33.77
4,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Caribbean Sea,D10/17/1992,75.22

In [3]:
print(sea_levels.columns)

Index(['Country', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source', 'CTS Code',
       'CTS Name', 'CTS Full Descriptor', 'Measure', 'Date', 'Value'],
      dtype='object')

In [4]:
#print(sea_levels.dtypes)
dates = sea_levels['Date'].str.split('/', expand = True)
sea_levels['Year'] = dates[2]
sea_levels.head()

,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,Measure,Date,Value,Year
0,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Arabian Sea,D10/17/1992,-62.65,1992
1,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Atlantic Ocean,D10/17/1992,2.94,1992
2,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Bay Bengal,D10/17/1992,9.81,1992
3,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Bering Sea,D10/17/1992,33.77,1992
4,World,NaN,WLD,Change in mean sea level: Sea level: TOPEX.Pos...,Millimeters,National Oceanic and Atmospheric Administratio...,ECCL,Change in Mean Sea Level,"Environment, Climate Change, Climate and Weath...",Caribbean Sea,D10/17/1992,75.22,1992

In [6]:
sea_levels = sea_levels.drop(columns = ['Country', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source', 'CTS Code', 'CTS Name', 'CTS Full Descriptor', 'Date'])
#sea_levels = sea_levels['Value'].fillna(0)
sea = sea_levels.pivot_table(index = 'Year', columns = 'Measure', values = 'Value', aggfunc = 'mean').reset_index(drop=False)
sea.head()

Measure,Year,Adriatic Sea,Andaman Sea,Arabian Sea,Atlantic Ocean,Baltic Sea,Bay Bengal,Bering Sea,Caribbean Sea,Gulf Mexico,...,North Sea,Pacific Ocean,Persian Gulf,Sea Japan,Sea Okhotsk,South China,Southern Ocean,Tropics,World,Yellow Sea
0,1992,55.627500,49.662500,-27.800000,-7.297500,32.397500,1.785000,-9.355000,29.832500,25.140000,...,28.410000,-10.395000,42.405000,47.142500,-15.260000,35.077500,-22.062500,-12.237500,-16.980000,14.005000
1,1993,-44.092353,-13.391176,-1.773529,-18.451176,-35.854706,-9.998824,-8.047647,-12.618235,-8.521765,...,-12.742941,-18.655294,-19.502353,-31.314118,-22.727647,-41.198235,-21.302941,-19.679412,-19.515294,-33.861176
2,1994,-15.201176,-46.644118,-1.000000,-14.960000,-11.372353,-20.913529,-9.874118,4.990588,-16.262941,...,-18.584118,-13.046471,1.206471,-5.090588,-17.860000,-36.115882,-17.141176,-16.079412,-14.818235,-7.620000
3,1995,-19.145484,-0.496875,3.837500,-8.192258,26.719375,1.188125,16.105484,-4.092903,-1.619375,...,3.219375,-10.195806,-1.201250,-17.354375,6.255625,-24.168065,-11.835484,-9.558065,-9.396129,-30.776452
4,1996,3.172353,11.837879,-6.553030,-7.121765,-107.402121,3.649394,35.661176,-18.427059,-32.423636,...,-34.576364,-5.246471,7.701212,-23.850303,11.711212,-12.504118,-9.185294,-4.570588,-5.847647,-17.937647

In [7]:
co_concentration = pd.read_csv('./Datasets/24_Atmospheric_CO2_Concentrations.csv')
co_concentration.head()

,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,Date,Value
0,World,NaN,WLD,Monthly Atmospheric Carbon Dioxide Concentrations,Parts Per Million,"Dr. Pieter Tans, National Oceanic and Atmosphe...",ECCA,Atmospheric Carbon Dioxide Concentrations,"Environment, Climate Change, Climate and Weath...",1958M03,315.71
1,World,NaN,WLD,Monthly Atmospheric Carbon Dioxide Concentrations,Parts Per Million,"Dr. Pieter Tans, National Oceanic and Atmosphe...",ECCA,Atmospheric Carbon Dioxide Concentrations,"Environment, Climate Change, Climate and Weath...",1958M04,317.45
2,World,NaN,WLD,Monthly Atmospheric Carbon Dioxide Concentrations,Parts Per Million,"Dr. Pieter Tans, National Oceanic and Atmosphe...",ECCA,Atmospheric Carbon Dioxide Concentrations,"Environment, Climate Change, Climate and Weath...",1958M05,317.51
3,World,NaN,WLD,Monthly Atmospheric Carbon Dioxide Concentrations,Parts Per Million,"Dr. Pieter Tans, National Oceanic and Atmosphe...",ECCA,Atmospheric Carbon Dioxide Concentrations,"Environment, Climate Change, Climate and Weath...",1958M06,317.27
4,World,NaN,WLD,Monthly Atmospheric Carbon Dioxide Concentrations,Parts Per Million,"Dr. Pieter Tans, National Oceanic and Atmosphe...",ECCA,Atmospheric Carbon Dioxide Concentrations,"Environment, Climate Change, Climate and Weath...",1958M07,315.87

In [8]:
print(co_concentration.columns)

Index(['Country', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source', 'CTS Code',
       'CTS Name', 'CTS Full Descriptor', 'Date', 'Value'],
      dtype='object')

In [10]:
year_month = co_concentration['Date'].str.split('M', expand = True)
co_concentration['Year'] = year_month[0]
co_concentration['month'] = year_month[1]
co_concentration = co_concentration.drop(columns = [ 'Country', 'ISO2', 'ISO3', 'Indicator', 'Source', 'CTS Code', 'CTS Name', 'CTS Full Descriptor','Date'])
co_concentration.head()

                Unit   Value  Year month
0  Parts Per Million  315.71  1958    03
1  Parts Per Million  317.45  1958    04
2  Parts Per Million  317.51  1958    05
3  Parts Per Million  317.27  1958    06
4  Parts Per Million  315.87  1958    07

In [11]:
co_concentration['Year'] = co_concentration['Year'].astype(int)
co_concentration['month'] = co_concentration['month'].astype(int)
co_concentration = co_concentration[co_concentration.Year >= 1992]
co_concentration.head()

                  Unit   Value  Year  month
800  Parts Per Million  356.34  1992      1
801            Percent    0.40  1992      1
802  Parts Per Million  357.21  1992      2
803            Percent    0.39  1992      2
804  Parts Per Million  357.97  1992      3

In [12]:
co_concentration = co_concentration.drop(columns = ['month'])
co_concentration = co_concentration.pivot_table(index = 'Year', columns = 'Unit', values = 'Value', aggfunc = 'mean')
co_concentration.head()

Unit  Parts Per Million   Percent
Year
1992         356.545000  0.237500
1993         357.215000  0.187500
1994         358.959167  0.488333
1995         360.968333  0.560833
1996         362.743333  0.492500

In [13]:
co_concentration = co_concentration.rename(columns = {'Parts Per Million': 'CO PPM', 'Percent':'CO Percent'}).reset_index(drop=False)
co_concentration.head()

Unit  Year      CO PPM  CO Percent
0     1992  356.545000    0.237500
1     1993  357.215000    0.187500
2     1994  358.959167    0.488333
3     1995  360.968333    0.560833
4     1996  362.743333    0.492500

In [14]:
sea.to_csv('./clean data/sea_level_changes.csv', index = False)
co_concentration.to_csv('./clean data/co_concentrations.csv', index = False)