In [2]:
import pandas as pd

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [3]:
# Load the original CSV file
file_path = "./Datasets/Forest and Carbon top 30.csv"
df = pd.read_csv(file_path)

In [4]:
df

,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,1992,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,"Afghanistan, Islamic Rep. of",AF,AFG,Forest area,1000 HA,Food and Agriculture Organization of the Unite...,ECMFF,NaN,"Environment, Climate Change, Mitigation, Fores...",1.208440e+03,...,1.208440e+03,1.208440e+03,1.208440e+03,1.208440e+03,1.208440e+03,1.208440e+03,1.208440e+03,1.208440e+03,1.208440e+03,1.208440e+03
1,"Afghanistan, Islamic Rep. of",AF,AFG,Index of forest extent,Index,Food and Agriculture Organization of the Unite...,ECMFE,NaN,"Environment, Climate Change, Mitigation, Fores...",1.000000e+02,...,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02
2,"Afghanistan, Islamic Rep. of",AF,AFG,Land area,1000 HA,Food and Agriculture Organization of the Unite...,ECMFL,NaN,"Environment, Climate Change, Mitigation, Fores...",6.522300e+04,...,6.522300e+04,6.522300e+04,6.522300e+04,6.522300e+04,6.522300e+04,6.522300e+04,6.522300e+04,6.522300e+04,6.522300e+04,6.522300e+04
3,"Afghanistan, Islamic Rep. of",AF,AFG,Share of forest area,Percent,Food and Agriculture Organization of the Unite...,ECMFD,NaN,"Environment, Climate Change, Mitigation, Fores...",1.852782e+00,...,1.852782e+00,1.852782e+00,1.852782e+00,1.852782e+00,1.852782e+00,1.852782e+00,1.852782e+00,1.852782e+00,1.852782e+00,1.852782e+00
4,Africa,NaN,AFRTMP,Carbon stocks in forests,Million tonnes,Food and Agriculture Organization of the Unite...,ECMFC,NaN,"Environment, Climate Change, Mitigation, Fores...",5.581176e+04,...,5.257869e+04,5.226680e+04,5.195491e+04,5.166661e+04,5.126544e+04,5.096040e+04,5.065436e+04,5.034383e+04,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1324,Zimbabwe,ZW,ZWE,Share of forest area,Percent,Food and Agriculture Organization of the Unite...,ECMFD,NaN,"Environment, Climate Change, Mitigation, Fores...",4.842843e+01,...,4.592754e+01,4.580845e+01,4.568936e+01,4.557027e+01,4.545118e+01,4.533209e+01,4.521300e+01,4.509391e+01,4.497482e+01,4.485573e+01
1325,World,NaN,WLD,Carbon stocks in forests,Million tonnes,Food and Agriculture Organization of the Unite...,ECMFC,NaN,"Environment, Climate Change, Mitigation, Fores...",2.969488e+05,...,2.941946e+05,2.943746e+05,2.945546e+05,2.947507e+05,2.944740e+05,2.944503e+05,2.942958e+05,2.941356e+05,NaN,NaN
1326,World,NaN,WLD,Forest area,1000 HA,Food and Agriculture Organization of the Unite...,ECMFF,NaN,"Environment, Climate Change, Mitigation, Fores...",4.220757e+06,...,4.092844e+06,4.088354e+06,4.083864e+06,4.080600e+06,4.073753e+06,4.068920e+06,4.063831e+06,4.058918e+06,4.053893e+06,4.048942e+06
1327,World,NaN,WLD,Index of carbon stocks in forests,Index,Food and Agriculture Organization of the Unite...,ECMFS,NaN,"Environment, Climate Change, Mitigation, Fores...",1.000000e+02,...,9.907248e+01,9.913310e+01,9.919371e+01,9.925976e+01,9.916659e+01,9.915860e+01,9.910657e+01,9.905263e+01,NaN,NaN
1328,World,NaN,WLD,Index of forest extent,Index,Food and Agriculture Organization of the Unite...,ECMFE,NaN,"Environment, Climate Change, Mitigation, Fores...",1.000000e+02,...,9.696943e+01,9.686305e+01,9.675667e+01,9.667934e+01,9.651714e+01,9.640261e+01,9.628204e+01,9.616564e+01,9.604659e+01,9.592930e+01

In [5]:
# Select specific columns
columns_to_keep = ['Country', 'Indicator'] + [f'{year}' for year in range(1992, 2023)]
df_filtered = df[columns_to_keep]

In [6]:
# Rename columns from 'FYear' to 'Year'
df_filtered.columns = ['Country', 'Indicator'] + [str(year) for year in range(1992, 2023)]

In [7]:
# Melt the DataFrame to long format
df_long = pd.melt(df_filtered, id_vars=['Country', 'Indicator'], var_name='Year', value_name='Value')

In [8]:
# Pivot the DataFrame to wide format based on 'Country', 'Year', and 'Indicator'
df_wide = df_long.pivot_table(index=['Country', 'Year'], columns='Indicator', values='Value', aggfunc='first').reset_index()

In [9]:
df_filtered_countries = df_wide

In [11]:
df_filtered_countries

Indicator,Country,Year,Carbon stocks in forests,Forest area,Index of carbon stocks in forests,Index of forest extent,Land area,Share of forest area
0,"Afghanistan, Islamic Rep. of",1992,NaN,1208.44,NaN,100.000000,65223.0,1.852782
1,"Afghanistan, Islamic Rep. of",1993,NaN,1208.44,NaN,100.000000,65223.0,1.852782
2,"Afghanistan, Islamic Rep. of",1994,NaN,1208.44,NaN,100.000000,65223.0,1.852782
3,"Afghanistan, Islamic Rep. of",1995,NaN,1208.44,NaN,100.000000,65223.0,1.852782
4,"Afghanistan, Islamic Rep. of",1996,NaN,1208.44,NaN,100.000000,65223.0,1.852782
...,...,...,...,...,...,...,...,...
7220,Zimbabwe,2018,1002.2235,17536.72,84.675304,93.606355,38685.0,45.332093
7221,Zimbabwe,2019,999.5906,17490.65,84.452857,93.360445,38685.0,45.213002
7222,Zimbabwe,2020,996.7833,17444.58,84.215675,93.114536,38685.0,45.093912
7223,Zimbabwe,2021,NaN,17398.51,NaN,92.868627,38685.0,44.974822
7224,Zimbabwe,2022,NaN,17352.44,NaN,92.622717,38685.0,44.855732

In [12]:
# Save the filtered dataset to a CSV file
csv_file_path = './clean data/Forest and Carbon top 30 clean.csv'
df_filtered_countries.to_csv(csv_file_path, index=False)

In [13]:
# Load the dataset
file_path = "./clean data/Forest and Carbon top 30 clean.csv"
df = pd.read_csv(file_path)

In [14]:

df

,Country,Year,Carbon stocks in forests,Forest area,Index of carbon stocks in forests,Index of forest extent,Land area,Share of forest area
0,"Afghanistan, Islamic Rep. of",1992,NaN,1208.44,NaN,100.000000,65223.0,1.852782
1,"Afghanistan, Islamic Rep. of",1993,NaN,1208.44,NaN,100.000000,65223.0,1.852782
2,"Afghanistan, Islamic Rep. of",1994,NaN,1208.44,NaN,100.000000,65223.0,1.852782
3,"Afghanistan, Islamic Rep. of",1995,NaN,1208.44,NaN,100.000000,65223.0,1.852782
4,"Afghanistan, Islamic Rep. of",1996,NaN,1208.44,NaN,100.000000,65223.0,1.852782
...,...,...,...,...,...,...,...,...
7220,Zimbabwe,2018,1002.2235,17536.72,84.675304,93.606355,38685.0,45.332093
7221,Zimbabwe,2019,999.5906,17490.65,84.452857,93.360445,38685.0,45.213002
7222,Zimbabwe,2020,996.7833,17444.58,84.215675,93.114536,38685.0,45.093912
7223,Zimbabwe,2021,NaN,17398.51,NaN,92.868627,38685.0,44.974822
7224,Zimbabwe,2022,NaN,17352.44,NaN,92.622717,38685.0,44.855732

In [15]:
# Define the geographically closest countries to Afghanistan for imputation
closest_geographical_countries = ['Iran, Islamic Rep. of', 'Pakistan', 'China, P.R.: Mainland', 'India']

In [16]:
# List of columns identified for imputation
columns_to_impute = ['Carbon stocks in forests', 'Index of carbon stocks in forests', 'Index of forest extent', 'Land area', 'Share of forest area']

In [17]:
# Perform imputation for each column
for column in columns_to_impute:
    for year in df['Year'].unique():
        # Calculate the mean for the geographically closest countries for the given year and column
        mean_value_geographical_countries = df[(df['Country'].isin(closest_geographical_countries)) & (df['Year'] == year)][column].mean()
        
        # Only impute this mean value for Afghanistan for the same year where the value is NaN
        afghanistan_nan_rows = df[(df['Country'] == 'Afghanistan, Islamic Rep. of') & (df['Year'] == year) & (df[column].isna())]
        if not afghanistan_nan_rows.empty:
            df.loc[afghanistan_nan_rows.index, column] = mean_value_geographical_countries

In [18]:
# Display the imputed dataset for Afghanistan
afghanistan_data_after_imputation = df[df['Country'] == 'Afghanistan, Islamic Rep. of']
afghanistan_data_after_imputation

,Country,Year,Carbon stocks in forests,Forest area,Index of carbon stocks in forests,Index of forest extent,Land area,Share of forest area
0,"Afghanistan, Islamic Rep. of",1992,2120.071125,1208.44,100.000000,100.0,65223.0,1.852782
1,"Afghanistan, Islamic Rep. of",1993,2160.349425,1208.44,101.072442,100.0,65223.0,1.852782
2,"Afghanistan, Islamic Rep. of",1994,2200.627750,1208.44,102.144893,100.0,65223.0,1.852782
3,"Afghanistan, Islamic Rep. of",1995,2240.906000,1208.44,103.217332,100.0,65223.0,1.852782
4,"Afghanistan, Islamic Rep. of",1996,2281.184300,1208.44,104.289774,100.0,65223.0,1.852782
5,"Afghanistan, Islamic Rep. of",1997,2321.462625,1208.44,105.362225,100.0,65223.0,1.852782
6,"Afghanistan, Islamic Rep. of",1998,2361.740925,1208.44,106.434667,100.0,65223.0,1.852782
7,"Afghanistan, Islamic Rep. of",1999,2402.019200,1208.44,107.507107,100.0,65223.0,1.852782
8,"Afghanistan, Islamic Rep. of",2000,2442.297475,1208.44,108.579546,100.0,65223.0,1.852782
9,"Afghanistan, Islamic Rep. of",2001,2467.687975,1208.44,109.226004,100.0,65223.0,1.852782
10,"Afghanistan, Islamic Rep. of",2002,2493.078475,1208.44,109.872462,100.0,65223.0,1.852782
11,"Afghanistan, Islamic Rep. of",2003,2518.468950,1208.44,110.518917,100.0,65223.0,1.852782
12,"Afghanistan, Islamic Rep. of",2004,2543.859475,1208.44,111.165376,100.0,65223.0,1.852782
13,"Afghanistan, Islamic Rep. of",2005,2569.249975,1208.44,111.811834,100.0,65223.0,1.852782
14,"Afghanistan, Islamic Rep. of",2006,2594.640425,1208.44,112.458288,100.0,65223.0,1.852782
15,"Afghanistan, Islamic Rep. of",2007,2620.030950,1208.44,113.104747,100.0,65223.0,1.852782
16,"Afghanistan, Islamic Rep. of",2008,2645.421425,1208.44,113.751201,100.0,65223.0,1.852782
17,"Afghanistan, Islamic Rep. of",2009,2670.811925,1208.44,114.397660,100.0,65223.0,1.852782
18,"Afghanistan, Islamic Rep. of",2010,2696.202425,1208.44,115.044118,100.0,65223.0,1.852782
19,"Afghanistan, Islamic Rep. of",2011,2749.213225,1208.44,116.021807,100.0,65223.0,1.852782
20,"Afghanistan, Islamic Rep. of",2012,2802.224025,1208.44,116.999496,100.0,65223.0,1.852782
21,"Afghanistan, Islamic Rep. of",2013,2855.234825,1208.44,117.977176,100.0,65223.0,1.852782
22,"Afghanistan, Islamic Rep. of",2014,2908.245625,1208.44,118.954865,100.0,65223.0,1.852782
23,"Afghanistan, Islamic Rep. of",2015,2961.256450,1208.44,119.932555,100.0,65223.0,1.852782
24,"Afghanistan, Islamic Rep. of",2016,3016.377600,1208.44,120.744521,100.0,65223.0,1.852782
25,"Afghanistan, Islamic Rep. of",2017,3061.368200,1208.44,121.585507,100.0,65223.0,1.852782
26,"Afghanistan, Islamic Rep. of",2018,3105.987825,1208.44,122.307197,100.0,65223.0,1.852782
27,"Afghanistan, Islamic Rep. of",2019,3149.965600,1208.44,123.019571,100.0,65223.0,1.852782
28,"Afghanistan, Islamic Rep. of",2020,3194.864850,1208.44,123.745838,100.0,65223.0,1.852782
29,"Afghanistan, Islamic Rep. of",2021,NaN,1208.44,NaN,100.0,65223.0,1.852782
30,"Afghanistan, Islamic Rep. of",2022,NaN,1208.44,NaN,100.0,65223.0,1.852782

In [19]:
df

,Country,Year,Carbon stocks in forests,Forest area,Index of carbon stocks in forests,Index of forest extent,Land area,Share of forest area
0,"Afghanistan, Islamic Rep. of",1992,2120.071125,1208.44,100.000000,100.000000,65223.0,1.852782
1,"Afghanistan, Islamic Rep. of",1993,2160.349425,1208.44,101.072442,100.000000,65223.0,1.852782
2,"Afghanistan, Islamic Rep. of",1994,2200.627750,1208.44,102.144893,100.000000,65223.0,1.852782
3,"Afghanistan, Islamic Rep. of",1995,2240.906000,1208.44,103.217332,100.000000,65223.0,1.852782
4,"Afghanistan, Islamic Rep. of",1996,2281.184300,1208.44,104.289774,100.000000,65223.0,1.852782
...,...,...,...,...,...,...,...,...
7220,Zimbabwe,2018,1002.223500,17536.72,84.675304,93.606355,38685.0,45.332093
7221,Zimbabwe,2019,999.590600,17490.65,84.452857,93.360445,38685.0,45.213002
7222,Zimbabwe,2020,996.783300,17444.58,84.215675,93.114536,38685.0,45.093912
7223,Zimbabwe,2021,NaN,17398.51,NaN,92.868627,38685.0,44.974822
7224,Zimbabwe,2022,NaN,17352.44,NaN,92.622717,38685.0,44.855732

In [20]:
# Define the path for the new CSV file
new_file_path = './clean data/Forest and Carbon top 30 clean imputed.csv'

# Save the updated dataset to the new CSV file
df.to_csv(new_file_path, index=False)